require("config.hi")
require("config.remap")
require("config.set")

vim.schedule(function()
    require("config.mini")
    require("config.lsp")
    require("config.treesitter")
    require("config.cmp")
    require("config.misc")
    require("config.dev")
end)
